config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/projects/new" => "projects#new", as: :new_project
  post "/projects" => "projects#create", as: :projects
  get "/projects/:id" => "projects#show", as: :project
  get "/projects" => "projects#index"
  get "/projects/:id/edit" => "projects#edit", as: :edit_project
  patch "/projects/:id" => "projects#update"
  delete "/projects/:id" => "projects#destroy"
resources :projects, only: [] do
  resources :tasks, only: [:new, :create, :update, :destroy]
    resources :discussions, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :favorites, only: [:create, :destroy]
end

resources :discussions, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :comments, only:[:new, :create, :update, :destroy, :edit]
end

resources :users, only: [:new, :create, :edit, :update]

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

get "users/:id/edit_password" => "users#edit_password", as: :edit_password
patch "users/:id/update_password" => "users#update_password"

resources :favorites, only: [:index]
  root 'welcome#index'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project

  has_many :comments, dependent: :destroy

  belongs_to :user

  validates :title, presence: true

  validates :body, length: { minimum: 5,
                             maximum: 300 }



end

app/controllers/discussions_controller.rb
  class DiscussionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

  def new
  end

  def create
    @project = Project.find params[:project_id]
      discussion_params = params.require(:discussion).permit([:title, :body])
    @discussion = Discussion.new(discussion_params)
    @discussion.project = @project
    @discussion.user = current_user
    respond_to do |format|
      if @discussion.save
        format.html {redirect_to project_path(@project)}
        format.js { render :discussion_create }
      else
        format.html {render "/projects/show"}
        format.js { render :discussion_not_create}
     end
    end
  end

  def destroy
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project) }
      format.js { render }
   end
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    discussion_params = params.require(:discussion).permit([:title, :body])
    @discussion = Discussion.find params[:id]
    @discussion.update(discussion_params)
    redirect_to project_path(@project)
  end

  def show
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
    @comment = Comment.new
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>">
  <p><%= link_to "Title: #{discussion.title}", project_discussion_path(@project, discussion)  %></p>
</div>
<hr>

app/views/discussions/_discussion_edit_form.html.erb
<%= simple_form_for [@project, @discussion] do |f|  %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.submit %>
<% end %>

app/views/discussions/_discussion_form.html.erb
<%= form_for [@project, @discussion] do |f|  %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/_discussion_new_form.html.erb
<%= @discussion.errors.full_messages.join(", ") %>

<%= simple_form_for [@project, @discussion], remote: true do |f|  %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/discussions/destroy.js.erb
$('#<%= dom_id(@discussion) %>').fadeOut(1000, function(){
  $(this).remove();
  window.location.href="<%= project_path(@project) %>"
});

app/views/discussions/discussion_create.js.erb
$('#discussion').prepend("<%= j render 'discussion', discussion: @discussion %>");

<% @discussion = Discussion.new %>

$('#discussion-form').html('<%= j render "discussion_new_form" %>');

app/views/discussions/discussion_not_create.js.erb
$('#discussion-form').html("<%= j render 'discussion_new_form' %>");

app/views/discussions/edit.html.erb
<h1>Update Discussion</h1>

<%= render "discussion_edit_form" %>

app/views/discussions/show.html.erb
<div id="<%= dom_id(@discussion) %>">
  <h1>Title: <%= @discussion.title %></h1>
  <h2>body: <%= @discussion.body %></h2>
  <%= button_to "Edit", edit_project_discussion_path(@project, @discussion),
                                                     method: :get %>

  <%= button_to "Delete", project_discussion_path(@project, @discussion),
                                                  method: :delete,
                                                  remote: true %>

  <div id="comment-form">
    <%= render "/comments/comment_form" %>
  </div>

  <h3>Comments</h3>
  
  <div id="comments">
    <% @discussion.comments.each do |com| %>
      <%= render "/comments/comments", comment: com %>
    <% end %>
  </div>
</div>