config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/projects/new" => "projects#new", as: :new_project
  post "/projects" => "projects#create", as: :projects
  get "/projects/:id" => "projects#show", as: :project
  get "/projects" => "projects#index"
  get "/projects/:id/edit" => "projects#edit", as: :edit_project
  patch "/projects/:id" => "projects#update"
  delete "/projects/:id" => "projects#destroy"
resources :projects, only: [] do
  resources :tasks, only: [:new, :create, :update, :destroy]
    resources :discussions, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :favorites, only: [:create, :destroy]
end

resources :discussions, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :comments, only:[:new, :create, :update, :destroy, :edit]
end

resources :users, only: [:new, :create, :edit, :update]

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

get "users/:id/edit_password" => "users#edit_password", as: :edit_password
patch "users/:id/update_password" => "users#update_password"

resources :favorites, only: [:index]
  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion

  belongs_to :user

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = Discussion.find params[:discussion_id]
    comments_params = params.require(:comment).permit([:body])
    @comment = @discussion.comments.new(comments_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
           if @discussion.user != current_user
              AnswersMailer.notify_discussion_owner(@comment).deliver_later
           end
        format.html { redirect_to project_discussion_path(@discussion.project, @discussion) }
        format.js { render :comment_successful }
      else
        format.js { render :comment_unsuccessful }
      end
    end
  end

  def edit
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
  end

  def update
    @discussion = Discussion.find params[:discussion_id]
    comments_params = params.require(:comment).permit([:body])
    @comment = Comment.find params[:id]
    @comment.update(comments_params)
    redirect_to project_path(@discussion.project)
  end

  def destroy
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
    @comment.destroy
    respond_to do |format|
    format.html { redirect_to project_discussion_path(@discussion.project, @discussion) }
    format.js { render }
   end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<%= @comment.errors.full_messages.join(", ") %>
<br>
<%= simple_form_for [@discussion, @comment], remote: true do |f| %>
    <%= f.input :body  %>
    <%= f.submit %>
<% end %>

app/views/comments/_comments.html.erb
<div id="<%= dom_id(comment) %>">
<%= comment.body %>
<%= link_to "Edit", edit_discussion_comment_path(@discussion, comment)  %>
<%= button_to "Delete", discussion_comment_path(@discussion, comment), method: :delete, remote: true %>
<hr>
</div>

app/views/comments/comment_successful.js.erb
$('#comments').append("<%= j render 'comments', comment: @comment %>");

<% @comment = Comment.new %>

$("#comment-form").html("<%= j render 'comment_form' %>");

app/views/comments/comment_unsuccessful.js.erb
$('#comment-form').html("<%= j render 'comment_form' %>");

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/comments/edit.html.erb
<h1>Update Comments</h1>

<%= render "comment_form" %>