config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/projects/new" => "projects#new", as: :new_project
  post "/projects" => "projects#create", as: :projects
  get "/projects/:id" => "projects#show", as: :project
  get "/projects" => "projects#index"
  get "/projects/:id/edit" => "projects#edit", as: :edit_project
  patch "/projects/:id" => "projects#update"
  delete "/projects/:id" => "projects#destroy"
resources :projects, only: [] do
  resources :tasks, only: [:new, :create, :update, :destroy]
    resources :discussions, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :favorites, only: [:create, :destroy]
end

resources :discussions, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :comments, only:[:new, :create, :update, :destroy, :edit]
end

resources :users, only: [:new, :create, :edit, :update]

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

get "users/:id/edit_password" => "users#edit_password", as: :edit_password
patch "users/:id/update_password" => "users#update_password"

resources :favorites, only: [:index]
  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  mount_uploader :image, ImageUploader
  mount_uploader :file, FileUploader

  validates :title, presence: true,
                    uniqueness: true

  validates :description, length: { minimum: 3 ,
                                    maximum: 255
                                       }
  validates :due_date, presence: true



  def favor_for(user)
    favorites.find_by_user_id user
  end

  def created_by?(current_user)
    user.id == current_user.id
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = Project.all

  end

  def new
    @project = Project.new
  end

  def create
    project_params
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project), notice: "New project has been added!!"
    else
      flash[:alert] = "Your project is not added, check the errors below"
      render :new
    end

  end

  def show
    @project = Project.find params[:id]
    @task = Task.new
    @discussion = Discussion.new
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    project_params
    @project = Project.find params[:id]
    if @project.update(project_params)
       redirect_to project_path(@project), notice: "Your project has been updated"
    else
       flash[:alert] = "Your project is not updated, check the errors below"
       render :edit
    end


  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path, notice: "Your Project has been removed!!"
  end

  private

  def project_params
    project_params = params.require(:project).permit([:title, :description, :due_date, :image, :file])
  end



end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= @project.errors.full_messages.join(" ") %>

<%= simple_form_for @project do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :due_date %>
  <%= f.input :image, multiple: true, hint: "jpg, jpeg, gif, png" %>
  <%= f.input :file, as: :file, hint: "pdf, doc, txt, html" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Update Your Project</h1>

<%= render "form" %>

app/views/projects/index.html.erb
<h1>Projects (<%= @projects.length %>)</h1>

<% @projects.each do |project| %>
<%= link_to project.title, project_path(project) %>
<% if can? :delete, project %>
<%= link_to "Delete", project_path(project),
                      method: :delete,
                      data: { confirm: "You Sure?" } %>
<% end %>
<hr>
<% end %>

app/views/projects/new.html.erb
<h1>Add New Projects</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<h1>Proejct: <%= @project.title %></h1>
<p>Description: <%= @project.description %></p>
<p>Due date: <%= @project.due_date %></p>
<p>Created by: <%= @project.user.full_name %></p>
<%= image_tag @project.image.url(:large) %>
<br>
  <%= link_to "File", @project.file.url, target: "_blank" %>
  <%= link_to "Edit", edit_project_path %>
  <%= link_to "Delete", project_path(@project),
                        method: :delete,
                        data: { confirm: "You Sure?" } %>
  <%= link_to "Add", new_project_path %>
<br>
<% favor = @project.favor_for(current_user) %>
<% created_by = @project.created_by?(current_user) %>
<% if favor %>
<p><%= link_to "Remove Favorite", project_favorite_path(@project, favor), method: :delete  %></p>
<% elsif !created_by %>
<p><%= link_to "Favorite", project_favorites_path(@project), method: :post %></p>
(<%= @project.favorites.count %>)
<% end %>

<br>
<hr>
  <h2>Add Discussions</h2>
  <div id="discussion-form">
  <%= render "/discussions/discussion_new_form" %>
</div>

<br>
<h2>Discussions</h2>
<div id="discussion">
<% @project.discussions.each do |discussion| %>
  <%= render "/discussions/discussion", discussion: discussion %>
<% end %>
</div>

<hr>
<h3>Add Tasks</h3>
<div id="task-form">
  <%= render "/tasks/task_form" %>
</div>

<h3>Incomplete</h3>
<div id="incomplete-tasks">
  <% @project.tasks.where("status = false").each do |task| %>
    <%= render "/tasks/incomplete", task: task %>
  <% end %>
</div>

<h3>complete</h3>
<div id="complete-tasks">
  <% @project.tasks.where("status = true").each do |task| %>
    <%= render "/tasks/complete", task: task %>
  <% end %>
</div>