config/routes.rb
Rails.application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/projects/new" => "projects#new", as: :new_project
  post "/projects" => "projects#create", as: :projects
  get "/projects/:id" => "projects#show", as: :project
  get "/projects" => "projects#index"
  get "/projects/:id/edit" => "projects#edit", as: :edit_project
  patch "/projects/:id" => "projects#update"
  delete "/projects/:id" => "projects#destroy"
resources :projects, only: [] do
  resources :tasks, only: [:new, :create, :update, :destroy]
    resources :discussions, only: [:new, :create, :show, :destroy, :update, :edit]
    resources :favorites, only: [:create, :destroy]
end

resources :discussions, only: [:new, :create, :update, :destroy, :edit, :show] do
    resources :comments, only:[:new, :create, :update, :destroy, :edit]
end

resources :users, only: [:new, :create, :edit, :update]

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

get "users/:id/edit_password" => "users#edit_password", as: :edit_password
patch "users/:id/update_password" => "users#update_password"

resources :favorites, only: [:index]
  root 'welcome#index'

end

app/views/layouts/_header.html.erb
<%= link_to "Sign Up", new_user_path %> |
<%= link_to "HOME", root_path %> |
<%= link_to "Projects", projects_path %> |
<%= link_to "Add Projects", new_project_path  %> |
<%= link_to "Sign In", new_session_path  %>
<% if current_user %> |
<%= link_to "Favorite Projects", favorites_path %>
<% end %>


<% if user_signed_in? %>
Hello! <%= link_to "#{current_user.first_name}", edit_user_path(current_user) %>
<%= link_to "Logout", sessions_path, method: :delete %>
<% end %>

<br>
<%= notice || alert %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pmtool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
  <%= yield %>
 </div>

</body>
</html>